=head1 Prereq

 mkdir ~/devel && cd ~/devel
 mkdir brnopm && cd brnopm
 git clone git://github.com/twitter/bootstrap.git
 git clone git@github.com:mj41/BrnoPM-Web.git

=head1 Devel

 vim caml/template/index.tpl
 perl caml/render.pl
 firefox static/index.html

=head1 Devel with PSGI server (autorefresh, just change the caml templates)

 cpanm --installdeps --with-develop .
 twiggy -p 5000 index.psgi
 firefox http://localhost:5000/index.html

=cut
